  
apiVersion: run.tanzu.vmware.com/v1alpha1
kind: TanzuKubernetesCluster
metadata:
  name: tkc-dirk-01
spec:
  distribution:
    version: v1.19
  topology:
    controlPlane:
      class: guaranteed-small
      count: 1
      storageClass: kubernetes-gold-storage-policy
    workers:
      class: guaranteed-small
      count: 1
      storageClass: kubernetes-gold-storage-policy
  settings:
    storage:
      classes: ["kubernetes-gold-storage-policy"]              #Named PVC storage classes
      defaultClass: kubernetes-gold-storage-policy             #Default PVC storage class
    network:
      cni:
        name: antrea                                           #antrea oder calico. Antrea ab v1.17.7 default
#      services:
#        cidrBlocks: ["198.51.100.0/12"]
#      pods:
#        cidrBlocks: ["192.0.2.0/16"]
#   distribution:
#    version: v1.18.5                                          #Bemerkung: Antrea statt Calico ab v1.17.7
