apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: tkc-dirk
  namespace: tkg-dirk
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["172.20.14.0/24"]
    pods:
      cidrBlocks: ["10.96.0.0/23"]
    serviceDomain: "cluster.local"
  topology:
    class: tanzukubernetescluster
    version: v1.23.8+vmware.2
    controlPlane:
      replicas: 1
    workers:
      machineDeployments:
        - class: node-pool
          name: node-pool-1
          replicas: 1
    variables:
      - name: vmClass
        value: best-effort-medium
      - name: storageClass
        value: avi-tanzu-vsan-storage-policy
      - name: defaultStorageClass
        value: avi-tanzu-vsan-storage-policy
